import React from 'react'
import Banner from '../components/Banner'

const Home = () => {
  return (
    <div className=''>
      <Banner />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus, ratione. Iure itaque veniam blanditiis dolorem? Modi ullam voluptas est mollitia earum rerum ea nemo ipsum. Corrupti voluptatibus, ducimus, dolorem voluptatem delectus ullam inventore expedita architecto mollitia nobis sequi voluptas hic voluptatum magni dolore temporibus nam sed tempora repellendus eligendi placeat. Accusantium corporis ullam distinctio officia quibusdam ea quas id molestiae atque dolorem ut qui reiciendis quod, facilis sunt nulla molestias animi nam ratione fugiat sit omnis vero? Perferendis fuga saepe nesciunt voluptatum at praesentium inventore incidunt quaerat fugiat est voluptas rerum accusantium, optio voluptatibus quas odio officiis ullam expedita cumque temporibus maiores placeat et tenetur facilis. Cum reprehenderit earum atque consequuntur quis? Accusamus consequuntur eveniet minima deserunt quaerat aliquid blanditiis incidunt nemo, veniam error beatae, eaque laboriosam molestias nam, ratione accusantium necessitatibus provident consectetur assumenda animi aspernatur laudantium. Vero esse enim architecto dolorum deserunt! Quasi hic repellendus nemo quas dolor porro unde in magni quos fugiat praesentium voluptatem nobis officia debitis, quidem eum, pariatur deleniti, ullam voluptatum adipisci. Iusto quam quasi nam quis ex eveniet? Optio a enim minima expedita quam ex quibusdam quasi consequuntur cumque corporis sapiente fugit dolores at, accusantium reiciendis inventore recusandae, animi impedit, fuga autem. Iure molestiae quam perspiciatis rerum nam. Vero ut eum alias blanditiis porro? Tempore nobis, aliquam vitae mollitia, facere recusandae adipisci provident eligendi nihil beatae autem. Deleniti excepturi molestias, reprehenderit blanditiis consequuntur maiores expedita suscipit incidunt pariatur eligendi dolores quod provident optio! Quod neque obcaecati odio necessitatibus veniam illum. Molestias iste, ducimus aperiam repellendus ipsam dolores recusandae quos assumenda hic sunt cum tempore excepturi, rerum dolorem quaerat omnis qui sed velit atque quasi similique. Eveniet quos voluptatem doloribus voluptatum optio illum necessitatibus nulla repellat provident dignissimos, quibusdam qui eligendi facilis enim magnam repellendus delectus, commodi excepturi consequuntur harum sunt. Ipsa, voluptates dolorem!</p>
    </div>
  )
}

export default Home